export const CLASS_TYPES = {
  GET_CLASSES: 'GET_CLASSES',
  CREATE_CLASS: 'CREATE_CLASS',
  RENAME_CLASS: 'RENAME_CLASS',
  JOIN_CLASS: 'JOIN_CLASS',
  GET_STUDENT_CLASSES: 'GET_STUDENT_CLASSES',
  CHANGE_CLASS_STATUS: 'CHANGE_CLASS_STATUS',
  FIRED_STUDENT: 'FIRED_STUDENT',
  DELETE_CLASS: 'DELETE_CLASS',
};
